// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSION: KVNamespace;
	NODE_VERSION: "22.13.0";
	PUBLIC_CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
}
