import { expect, test } from "@playwright/test"

test.describe("記録操作", () => {
  test("記録の追加から削除まで", async ({ page }) => {
    await page.goto("/record")
    await expect(page.getByText("登録日月火水木金土")).toBeVisible()
    const day1Element = await page.waitForSelector("div:has-text('1')")
    await day1Element.click()
    await expect(page.getByRole("main")).toContainText("この日の活動記録がありません。")
    await page.getByRole("button", { name: "記録を追加" }).click()
    await page.getByRole("button", { name: "一時保存" }).click()
    const day2Element = await page.waitForSelector("div:has-text('2')")
    await day2Element.click()
    await expect(page.getByRole("main")).toContainText("この日の活動記録がありません。")
    await page.getByRole("button", { name: "記録を追加" }).click()
    await expect(page.getByText("時間")).toBeVisible()
    await page.getByRole("button", { name: "戻る" }).click()
    await page.getByRole("button", { name: "登録" }).click()
    await page.goto("/record")
    const summaryElement = await page.waitForSelector("text=1合計 1.5h")
    await summaryElement.click()
    await expect(page.getByText("時間")).toBeVisible()
    await page.getByRole("button", { name: "戻る" }).click()
    const day2Element2 = await page.waitForSelector("div:has-text('2')")
    await day2Element2.click()
    await expect(page.getByText("この日の活動記録がありません。")).toBeVisible()
    await page.getByRole("button", { name: "戻る" }).click()
    await expect(page.getByText("1合計 1.5h")).toBeVisible()
    const summaryElement2 = await page.waitForSelector("text=1合計 1.5h")
    await summaryElement2.click()
    await page.getByRole("button", { name: "削除" }).click()
    await page.getByRole("button", { name: "一時保存" }).click()
    await page.getByRole("button", { name: "登録" }).click()
    const day1Element2 = await page.waitForSelector("div:has-text('1')")
    await day1Element2.click()
    await page.getByText("この日の活動記録がありません。").click()
    await expect(page.getByText("この日の活動記録がありません。")).toBeVisible()
  })
})
