name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged != true
    environment: preview
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Set up Node 22.13.0
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.0'
      - name: Install dependencies
        run: npm install
      - name: Run lint and format check
        run: npm run ci:lint
      - name: Add .env variables
        run: |
          echo "" > .env
          echo "PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> .env
          echo "TURSO_DATABASE_URL=${{ secrets.TURSO_DATABASE_URL }}" >> .env
          echo "TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }}" >> .env
      - name: Build
        run: npm run build --remote
      - name: Rename Projects Name
        run: |
          sed -i 's/"name": "record"/"name": "record-preview"/g' wrangler.jsonc
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            deploy --name record-preview
          secrets: |
            PUBLIC_CLERK_PUBLISHABLE_KEY
            CLERK_SECRET_KEY
            TURSO_DATABASE_URL
            TURSO_AUTH_TOKEN
        env:
          PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
