name: Preview

on:
  push:
    branches:
      - 'preview'

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: preview
    name: Deploy
    permissions:
      contents: read
      deployments: write
    env:
      PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.PUBLIC_CLERK_PUBLISHABLE_KEY }}
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Set up Node 22.13.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --remote
      - name: Deploy to Preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env preview